const GAME_ACTIONS = Object.freeze({
  TOGGLE_PLACEMENT: "TOGGLE_PLACEMENT",
  SELECT_TOWER_TYPE: "SELECT_TOWER_TYPE",
  UPGRADE_SELECTED: "UPGRADE_SELECTED",
  SELL_SELECTED: "SELL_SELECTED",
  CYCLE_TARGETING: "CYCLE_TARGETING",
  TOGGLE_PAUSE: "TOGGLE_PAUSE",
  TOGGLE_HELP: "TOGGLE_HELP",
  CANCEL: "CANCEL",
  START_WAVE: "START_WAVE",
  PRIMARY_AT: "PRIMARY_AT",
  SECONDARY_AT: "SECONDARY_AT",
  POINTER_MOVED: "POINTER_MOVED",
  TOUCH_AT: "TOUCH_AT",
  CONFIRM_PLACEMENT: "CONFIRM_PLACEMENT",
});

const TOUCH_GHOST_OFFSET = 56;

export { GAME_ACTIONS, TOUCH_GHOST_OFFSET };
